# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

doNotExceed = 4000000
counter = 0
a = 1
b = 2
while a < doNotExceed:
	print(a)
	if a % 2 == 0:
		counter += a
	a += b
	a, b = b, a
print("Sum of even Fionacci Numbers < 4M: " + str(counter))